# Spring Boot configuration
spring:
  # Database
  profiles:
    active: "development"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/profile
    username: postgres
    password: andjela1999
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
    generate-ddl: true
  #swagger v3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Server configuration
server:
  port: 8080 #set your port


---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/profile
---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://db:5432/profile